# Lovsamling 

```{r, echo=FALSE, results='asis'}
cat(readLines('np.html'))
```



<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=177079" target="_blank">Aftaleloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=2664" target="_blank">Arveloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=210090" target="_blank">Betalingsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=84351" target="_blank">Checkloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/r0710.aspx?id=201319" target="_blank">Databeskyttelsesloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=59516" target="_blank">Danske Lov - sammenskrivning af Kong Christian den femtis danske lov</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=25854" target="_blank">E-handelsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209437" target="_blank">Erhvervsvirksomhedsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=192383" target="_blank">Erstatningsansvarsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=160666" target="_blank">Forbrugeraftaleloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=164748" target="_blank">Forbrugerbeskyttelse ved erhvervelse af fast ejendom mv</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=169709" target="_blank">Forbrugerklageloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=143090" target="_blank">Forsikringsaftaleloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=197146" target="_blank">Forsikringsformidlingsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=210533" target="_blank">Bekendtgørelse om god skik for forsikringsdistributører</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=164746" target="_blank">Forældelsesloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=204976" target="_blank">Færdselsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=45902" target="_blank">Grundloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=143107" target="_blank">Gældsbrevsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=194694" target="_blank">Hundeloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209981" target="_blank">Hvidvaskloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=174776" target="_blank">Høstpantebrevsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=143233" target="_blank">Inkassoloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=158134" target="_blank">Konkursloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209544" target="_blank">Kreditaftaleloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=142961" target="_blank">Købeloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=210121" target="_blank">Lejeloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=203465" target="_blank">Lov om andelsboligforeninger og andre bofællesskaber</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209982" target="_blank">Lov om finansiel virksomhed</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=177565" target="_blank">Bekendtgørelse om god skik for finansielle virksomheder</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=177566" target="_blank">Bekendtgørelse om god skik for finansielle rådgivere</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=205005" target="_blank">Bekendtgørelse om god skik for boligkredit</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=163284" target="_blank">Lov om formidling af fast ejendom</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=166035" target="_blank">Formidlingsbekendtgørelsen</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209786" target="_blank">Lov om ægtefællers økonomiske forhold</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209754" target="_blank">Lov om ægteskabets indgåelse og opløsning</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=188880" target="_blank">Markedsføringsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=142962" target="_blank">Renteloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209542" target="_blank">Retsplejeloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209846"
target="_blank">Selskabsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=209398"
target="_blank">Straffeloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=142900" target="_blank">Tinglysningsloven</a></h3>
<h3><a href="https://www.retsinformation.dk/Forms/R0710.aspx?id=2681" target="_blank">Værgemålsloven</a></h3>











